config/routes.rb
Clf004::Application.routes.draw do
  get "welcome/index"
  get "welcome/wizard", as: :wizard_welcome
  get "welcome/wizard_bar", as: :wizard_bar_welcome

  devise_for :users

  root :to => 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # https://github.com/martinrehfeld/role_model
  include RoleModel

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  # optionally set the integer attribute to store the roles in,
  # :roles_mask is the default
  roles_attribute :roles_mask

  # declare the valid roles -- do not change the order if you add more
  # roles later, always append them at the end!
  roles :admin, :manager, :associate
end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
  attr_accessible :description, :durability, :name, :weight, :zombie_id

  # def clear
  # def empty?
  # def size
  # def find(…)
  # def where(…)
  # def exists?(…)
  # def build(attributes = {}, …)
  # def create(attributes = {})
  # def <<(object, …)
  # def delete(object, …)
end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  include RankyClothes

  attr_accessible :age, :description, :graveyard, :name

  has_many :weapons

  has_clothes :smelly_shirt, :dingy_pants, :fishy_socks

  # def weapons(force_reload = false)
  # def weapons=objects
  # def weapons_singular_ids
  # def weapons_singular_ids=ids

  # @weapons created, an Array
  # def clear
  # def empty?
  # def size
  # def find(…)
  # def where(…)
  # def exists?(…)
  # def build(attributes = {}, …)
  # def create(attributes = {})
  # def <<(object, …)
  # def delete(object, …)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!, except: [:sign_in, :sign_out]
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  def index
  end
  def wizard
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def js_void
    "javascript: xvoid();"
  end

  def form_type(obj)
    if(obj.new_record?)
      "new-form new-#{obj.class.name.downcase}"
    else
      "edit-form edit-#{obj.class.name.downcase}"
    end
  end

  def form_id(obj)
    if(obj.new_record?)
      "new-#{obj.class.name.downcase}"
    else
      "edit-#{obj.class.name.downcase}"
    end
  end

  def backbone_attr(name)
    "<%= #{name} %>"
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Clf004</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <style type="text/css">
    /*   height: 300px; /* row.navbar-main.height + row.navbar-main.padding-bottom = >this< */ 
    /* .header{ */
    /*   background-color: blue; */
    /*   color: white;  */
    /*   position: absolute; */
    /*   width: 100%; */
    /*   left: 0; */
    /*   top: 0; */
    /*   padding: 0; */
    /*   margin: 0; */
    /*   z-index: -10; */

    /* } */

    .header {
      background-color: blue; 
      color: #FFFFFF;
      padding: 20px 0;
      position: relative;
    }

    .header.narrow {
      text-align: center;
      margin-left: -20px;
      margin-right: -20px;
      margin-top: -20px;
      padding: 20px 20px;
    }


    /* space at top of main body */
    .container.controller-messages{
      margin-top: 2em;
    }

    /* space at bottom of main body */
    .row.main-content{
      margin-bottom: 2em;
    }

    .header .header-content{
      margin-top: 4em;
      margin-left: 4em;
    }
    .header .header-content p.lead{
      font-size: 20pt;
    }
    .header .header-content h1{
      font-size: 50pt;
      line-height: 70px;
    }

    .header .header-content.narrow{
      padding-left: 0;
      padding-right: 0;
      margin-left: 0;
      margin-right: 0;
      margin-top: 0;
    }
    .header .header-content.narrow h1{
      font-size: 40pt;
      text-align: center; 
    }
    .header .header-content.narrow p.lead{
      font-size: 16pt;
      text-align: center; 
    }

    #page-navigation ul li.active a{
      background-color: blue; 
      color: white; 
      border: blue; 
    }
    #page-navigation ul li.active i{
      background-image: url("/assets/img/glyphicons-halflings-white.png");
    }

    ul.pager.wizard li.groupdwleft{
      float: left; 
    }
    ul.pager.wizard li.pull-right{
      float: right; 
    }
  </style>

  <!-- http://www.seabreezecomputers.com/tips/mobile-css.htm -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes" /> 
</head>
<body>

    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
      <div class="container">
       
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </a>
       
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Project name", root_path, class: "brand" %>
       
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class="nav">
        <li><%= link_to "Home", root_path(anchor: "top-nav-home") %></li>
        <li><%= link_to "Wizard", wizard_welcome_path(anchor: "top-nav-wizard") %></li>
        <li><%= link_to "Wizard Bar", wizard_bar_welcome_path(anchor: "top-nav-wizard-bar") %></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>

        <% if(current_user) %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end -%>

        </ul>
      </div>
       
      </div>
      </div>
    </div>

  <div class="header">
    <div class=" header-content">
      <h1>Project Name</h1>
      <p class="lead">Aenean commodo ligula eget dolor aenean massa</p>
    </div>
  </div>

  <div class="container controller-messages">
    <div class="row">
      <div class="span12 ">
          <p class="alert alert-success" style="<%= notice.nil? ? "display: none; " : ""%>"><%= notice %></p>
          <p class="alert alert-error" style="<%= alert.nil? ? "display: none; " : ""%>"><%= alert %></p>
      </div>
    </div>
  </div>

  <div class="container">
  <div class="row main-content">
    <div class="span12 ">
      <%= yield %>
    </div>
  </div>
  </div>

</body>
</html>

<script type="text/javascript">
  $(document).ready(function(){
    // same as row.navbar-main.padding-bottom
    $('.page-navigation').affix({offset: 260});

    // update side-bar navigation to reflect current section of page
    $('body').scrollspy({target: '#page-navigation'});
    $('[data-spy="scroll"]').each(function () {
      var $spy = $(this).scrollspy('refresh')
    });
  });

  $(document).ready(function(){
    var va = new ViewAdjustment();
    va.add(".page-navigation", adjust_page_navigation);
    va.add(".header .header-content, ul.pager.wizard li", function(prop, win){
      if($(win).width() < 750){
        $(prop).addClass("narrow");
      } else {
        $(prop).removeClass("narrow");
      }
    });
    va.add(".navbar-main .navbar", function(prop, win){
      if($(win).width() < 750){
        $(prop).css("position", "static");
      } else {
        $(prop).css("position", "fixed");
      }
    });
    va.add(".header .header-content, ul.pager.wizard li, .header", function(prop, win){
      if($(win).width() < 980){
        $(prop).addClass("narrow");
      } else {
        $(prop).removeClass("narrow");
      }
    });

    

    $(window).resize(function(){va.adjustments(this)});
    $(window).scroll(function(){va.adjustments(this)});
    va.adjustments(window);

    // indicate which top navigation menu item is being displayed
    var top_nav_hash = location.hash.slice(1);
    $("[href $= '" + top_nav_hash + "']").closest("li").addClass("active");
  });

</script>

app/views/welcome/index.html.erb
  <div class="row">
    <div class="span12">
      <div class="hero-unit">
        <h1>Hello, world!</h1>
        <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <p><a class="btn btn-primary btn-large">Learn more</a></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span4">
      <div class="well">
        <h2>Admin</h2>
      </div>
    </div>
    <div class="span4">
      <div class="well">
        <h2>Manager</h2>
      </div>
    </div>
    <div class="span4">
      <div class="well">
        <h2>Associate</h2>
      </div>
    </div>
  </div>

app/views/welcome/wizard.html.erb
<div class="row">
  <div class="span3" style="">

    <div id="page-navigation">
    <ul class="nav nav-tabs nav-stacked page-navigation">
      <li><a href="#home">Home<i class="icon-chevron-right pull-right"></i></a></li>
      <li><a href="#profile">Profile<i class="icon-chevron-right pull-right"></i></a></li>
      <li><a href="#messages">Messages<i class="icon-chevron-right pull-right"></i></a></li>
    </ul>
    </div>

  </div>

  <div class="span9" style="">
            <div class="xscrollspy-example">
              <h4 id="home">@home</h4>
              <p>Ad leggings keytar, brunch id art party dolor labore. Pitchfork yr enim lo-fi before they sold out qui. Tumblr farm-to-table bicycle rights whatever. Anim keffiyeh carles cardigan. Velit seitan mcsweeney's photo booth 3 wolf moon irure. Cosby sweater lomo jean shorts, williamsburg hoodie minim qui you probably haven't heard of them et cardigan trust fund culpa biodiesel wes anderson aesthetic. Nihil tattooed accusamus, cred irony biodiesel keffiyeh artisan ullamco consequat.</p>
              <h4 id="profile">@profile</h4>
              <p>Veniam marfa mustache skateboard, adipisicing fugiat velit pitchfork beard. Freegan beard aliqua cupidatat mcsweeney's vero. Cupidatat four loko nisi, ea helvetica nulla carles. Tattooed cosby sweater food truck, mcsweeney's quis non freegan vinyl. Lo-fi wes anderson +1 sartorial. Carles non aesthetic exercitation quis gentrify. Brooklyn adipisicing craft beer vice keytar deserunt.</p>
              <div style="height: 1000px; width: 100%; background-color: gray; "></div>
              <h4 id="one">one</h4>
              <p>Occaecat commodo aliqua delectus. Fap craft beer deserunt skateboard ea. Lomo bicycle rights adipisicing banh mi, velit ea sunt next level locavore single-origin coffee in magna veniam. High life id vinyl, echo park consequat quis aliquip banh mi pitchfork. Vero VHS est adipisicing. Consectetur nisi DIY minim messenger bag. Cred ex in, sustainable delectus consectetur fanny pack iphone.</p>
              <div style="height: 1000px; width: 100%; background-color: gray; "></div>
              <h4 id="two">two</h4>
              <p>In incididunt echo park, officia deserunt mcsweeney's proident master cleanse thundercats sapiente veniam. Excepteur VHS elit, proident shoreditch +1 biodiesel laborum craft beer. Single-origin coffee wayfarers irure four loko, cupidatat terry richardson master cleanse. Assumenda you probably haven't heard of them art party fanny pack, tattooed nulla cardigan tempor ad. Proident wolf nesciunt sartorial keffiyeh eu banh mi sustainable. Elit wolf voluptate, lo-fi ea portland before they sold out four loko. Locavore enim nostrud mlkshk brooklyn nesciunt.</p>
              <div style="height: 1000px; width: 100%; background-color: gray; "></div>
              <h4 id="messages">@messages</h4>
              <p>Ad leggings keytar, brunch id art party dolor labore. Pitchfork yr enim lo-fi before they sold out qui. Tumblr farm-to-table bicycle rights whatever. Anim keffiyeh carles cardigan. Velit seitan mcsweeney's photo booth 3 wolf moon irure. Cosby sweater lomo jean shorts, williamsburg hoodie minim qui you probably haven't heard of them et cardigan trust fund culpa biodiesel wes anderson aesthetic. Nihil tattooed accusamus, cred irony biodiesel keffiyeh artisan ullamco consequat.</p>
              <p>Keytar twee blog, culpa messenger bag marfa whatever delectus food truck. Sapiente synth id assumenda. Locavore sed helvetica cliche irony, thundercats you probably haven't heard of them consequat hoodie gluten-free lo-fi fap aliquip. Labore elit placeat before they sold out, terry richardson proident brunch nesciunt quis cosby sweater pariatur keffiyeh ut helvetica artisan. Cardigan craft beer seitan readymade velit. VHS chambray laboris tempor veniam. Anim mollit minim commodo ullamco thundercats.
              </p>
            </div>
          </div>

  </div>
</div>

app/views/welcome/wizard_bar.html.erb
<style type="text/css">
  .row.sample-section div{
    text-align: center; 
  }
</style>

    <div id="rootwizard">
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <ul>
              <li><a href="#tab1" data-toggle="tab">First</a></li>
              <li><a href="#tab2" data-toggle="tab">Second</a></li>
              <li><a href="#tab3" data-toggle="tab">Third</a></li>
              <li><a href="#tab4" data-toggle="tab">Forth</a></li>
              <li><a href="#tab5" data-toggle="tab">Fifth</a></li>
              <li><a href="#tab6" data-toggle="tab">Sixth</a></li>
              <li><a href="#tab7" data-toggle="tab">Seventh</a></li>
            </ul>
          </div>
        </div>

        <!-- div id="bar" class="progress progress-striped active" -->
        <div id="bar" class="progress progress active">
          <div class="bar"></div>
        </div>

        <div class="tab-content">
          <div class="tab-pane" id="tab1">
          1
          </div>

          <div class="tab-pane" id="tab2">
          <p>
          <input type='text' name='name' id='name' placeholder='Enter Your Name'>
          </p>
          </div>

          <div class="tab-pane" id="tab3">
          3
          </div>

          <div class="tab-pane" id="tab4">
            <div class="row sample-section">
              <div class="span4" style="">
                <h1>One</h1>
                <div class="well">1</div>
              </div>
              <div class="span4" style="">
                <h1>Two</h1>
                <div class="well">2</div>
              </div>
              <div class="span4" style="">
                <h1>Three</h1>
                <div class="well">3</div>
              </div>
            </div>
          </div>

          <div class="tab-pane" id="tab5">
          5
          </div>
          <div class="tab-pane" id="tab6">
          6
          </div>
          <div class="tab-pane" id="tab7">
          7
          </div>
          <ul class="pager wizard">
            <li class="group pull-left" >
              <ul>
              <li class="first"><a href="#">First</a></li>
              <li class="previous"><a href="#">Previous</a></li>
              </ul>
            </li>

            <li class="group pull-right" >
              <ul>
              <li class="next"><a href="#">Next</a></li>
              <li class="last"><a href="#">Last</a></li>
              <li class="finish save" ><a href="#">Save</a></li>
              </ul>
            </li>
          </ul>
        </div>	
      </div>	
    </div>



<script type="text/javascript">
    $(document).ready(function() {
    $('#rootwizard').bootstrapWizard({onNext: function(tab, navigation, index) {
      if(index==2) {
      // Make sure we entered the name
      if(!$('#name').val()) {
      alert('You must enter your name');
      $('#name').focus();
      return false;
      }
      }
      // Set the name for the next tab
      $('#tab3').html('Hello, ' + $('#name').val());

    }, onTabShow: function(tab, navigation, index) {
      var $total = navigation.find('li').length;
      var $current = index+1;
      var $percent = ($current/$total) * 100;
      $('#rootwizard').find('.bar').css({width:$percent+'%'});

    	// If it's the last tab then hide the last button and show the finish instead
      if($current >= $total) {
        $('#rootwizard').find('.pager .next').addClass("disabled");
        $('#rootwizard').find('.pager .finish').removeClass("disabled");
        $('#rootwizard').find('.pager .last').addClass("disabled");
      } else {
        $('#rootwizard').find('.pager .next').removeClass("disabled");
        $('#rootwizard').find('.pager .last').removeClass("disabled");
        $('#rootwizard').find('.pager .finish').addClass("disabled");
      }

      if($('#rootwizard .pager .previous').hasClass("disabled")){
        $('#rootwizard .pager .first').addClass("disabled");
      } else {
        $('#rootwizard .pager .first').removeClass("disabled");
      }
      
    }});


  	$('#rootwizard .finish').click(function() {
      alert('Finished!, Starting over!');
      $('#rootwizard').find("a[href*='tab1']").trigger('click');
    });

    $(".accordion-toggle").click(function(){
      $(".collapse.in").collapse("hide");
    });

    });
</script>